name: Python CI # workflow name

# events -> push, pull, merge, delete
# push, pull_request -> based on events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

## multiple jobs we can run

jobs:
  test:
    runs-on: ubuntu-latest # it runs on containers with this OS

    steps:
      - name: Check out code
        uses: actions/checkout@v2 # pre-built action

      - name: Set up Python # setting up python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies # installing required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests # running test cases
        run: pytest
